image: node:14.5.0

clone:
  depth: full
pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - node -v
          - npm ci
          - npm run build
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
